repos:
  - repo: local
    hooks:
      - id: kicad-erc
        name: KiCad ERC
        entry: make erc
        language: system
        pass_filenames: false
        files: \.(kicad_sch|kicad_pcb|kicad_pro)$
  - repo: local
    hooks:
      - id: kicad-artifacts
        name: KiCad Artifacts
        entry: artifacts-with-diff-check
        language: system
        pass_filenames: false
        files: \.(kicad_sch|kicad_pcb|kicad_pro)$
