name: Generate KiCad artifacts

on:
  push:
    branches:
      - main

    # This is needed, otherwise commiting fresh artifacts will trigger this job again
    paths-ignore:
      - "static/**"

  workflow_dispatch:

env:
  STATIC_DIR: "static"

jobs:
  build:
    name: Generate KiCad artifacts
    runs-on: ubuntu-latest
    container:
      image: "kicad/kicad:9.0"
      options: --user root
    steps:
      - uses: actions/checkout@v4

      - name: Fix Git repo ownership
        run: |
          # this is to fix GIT not liking owner of the checkout dir
          chown -R $(id -u):$(id -g) $PWD

      - name: Install dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          apt update && apt install make csvkit -y

      - name: Link KiCad .config dir to root equivalent
        run: |
          mkdir -p ~/.config
          ln -s /home/kicad/.config/kicad ~/.config/kicad

      - name: Ensure output dir exists
        run: mkdir -p ${{ env.STATIC_DIR }}

      - name: Generate artifacts
        run: |
          make artifacts STATIC_DIR=${{ env.STATIC_DIR }}

      - name: Check diff for create date changes
        run: |
          if [ -n "$(git diff --text --ignore-matching-lines='^\/CreationDate \(D:' --ignore-matching-lines='^<title>SVG Image created as .+.svg date')" ]; then
            echo "Detected relevant artifact changes"
          else
            echo "No relevant changes detected. Cleaning repo state."
            git restore ${{ env.STATIC_DIR }}
          fi

      - name: Create pull request
        id: create-pull-request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.AMP_ARTIFACT_UPDATE_GITHUB_TOKEN }}
          branch: update-kicad-artifacts
          commit-message: Update KiCad artifacts
          title: Update KiCad artifacts
          body: |
            ## Beep boop, fresh artifacts 🤖. 

            KiCad project sources have changed, fresh artifacts incoming ♻️!

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request

      - uses: peter-evans/enable-pull-request-automerge@v3
        if: ${{ steps.create-pull-request.outputs.pull-request-number }}
        with:
          token: ${{ secrets.AMP_ARTIFACT_UPDATE_GITHUB_TOKEN }}
          pull-request-number: ${{ steps.create-pull-request.outputs.pull-request-number }}
