name: Generate KiCad artifacts

on:
  push:
    branches:
      - main

    # This is needed, otherwise commiting fresh artifacts will trigger this job again
    paths-ignore:
      - "static/**"

env:
  STATIC_DIR: "static"

jobs:
  build:
    name: Generate KiCad artifacts
    runs-on: ubuntu-latest
    permissions: # Needed for PR creation
      contents: write
      pull-requests: write
    container:
      image: "kicad/kicad:9.0"
      options: --user root
    steps:
      - uses: actions/checkout@v4

      - name: Fix Git repo ownership
        run: |
          # this is to fix GIT not liking owner of the checkout dir
          chown -R $(id -u):$(id -g) $PWD

      - name: Install dependencies
        run: |
          apt update && apt install make -y

      - name: Link KiCad .config dir to root equivalent
        run: |
          mkdir -p ~/.config
          ln -s /home/kicad/.config/kicad ~/.config/kicad

      - name: Ensure output dir exists
        run: mkdir -p ${{ env.STATIC_DIR }}

      - name: Generate artifacts
        run: |
          make artifacts STATIC_DIR=${{ env.STATIC_DIR }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: "kicad_artifacts"
          path: "${{ env.STATIC_DIR }}"

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: update-kicad-artifacts
          commit-message: Update dependencies
          title: Update dependencies
          body: |
            ## Beep boop, fresh artifacts 🤖. 

            KiCad project sources have changed, fresh artifacts incoming ♻️!

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
